package com.example.counter.challenge;

import com.example.counter.user.User;
import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@Entity
@Table(name = "challenges")
public class Challenge {
    @Id
    @Column(name = "challenge_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long challengeId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(nullable = false)
    private String name;

    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    @Column(name = "duration_days", nullable = false)
    private Integer durationDays;

    @Column(name = "end_date", nullable = false, insertable = false, updatable = false)
    private LocalDate endDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "schedule_status", nullable = false, columnDefinition = "challenge_status")
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    private ChallengeStatus scheduleStatus = ChallengeStatus.scheduled;

    @Enumerated(EnumType.STRING)
    @Column(name = "completion", nullable = false, columnDefinition = "completion_status")
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    private CompletionStatus completion = CompletionStatus.not_started;

    @Column(name = "success_percent", nullable = false)
    private Integer successPercent = 0;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @OneToMany(mappedBy = "challenge", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ChallengeHabits> challengeHabits = new ArrayList<>();

    // Constructors
    public Challenge() {
        this.createdAt = getIndiaTimestamp();
        this.updatedAt = getIndiaTimestamp();
    }

    public Challenge(User user, String name, LocalDate startDate, Integer durationDays) {
        this.user = user;
        this.name = name;
        this.startDate = startDate;
        this.durationDays = durationDays;
        // endDate is auto-generated by the database
        this.createdAt = getIndiaTimestamp();
        this.updatedAt = getIndiaTimestamp();
        // Don't call updateStatus() here since endDate is not yet available
        // Status will be updated after the entity is saved and endDate is generated
        updateStatus(durationDays);
    }
    
    // Helper method to get current timestamp in India timezone
    private OffsetDateTime getIndiaTimestamp() {
        ZoneId indiaZone = ZoneId.of("Asia/Kolkata");
        return OffsetDateTime.now(indiaZone);
    }

    // Method to update challenge status based on current date
    public void updateStatus(Integer durationDays) {
        LocalDate today = LocalDate.now();
        
        if (startDate.isAfter(today)) {
            this.scheduleStatus = ChallengeStatus.scheduled;
        } else if (startDate.isEqual(today) || (startDate.isBefore(today) && startDate.plusDays(durationDays).isAfter(today))) {
            this.scheduleStatus = ChallengeStatus.active;
        } else {
            this.scheduleStatus = ChallengeStatus.expired;
        }
        
        this.updatedAt = getIndiaTimestamp();
    }

    // Getters and setters
    public Long getChallengeId() {
        return challengeId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
        this.updatedAt = getIndiaTimestamp();
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
        // endDate is auto-generated by the database
        updateStatus(durationDays);
    }

    public Integer getDurationDays() {
        return durationDays;
    }

    public void setDurationDays(Integer durationDays) {
        this.durationDays = durationDays;
        // endDate is auto-generated by the database
        updateStatus(durationDays);
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public ChallengeStatus getScheduleStatus() {
        return scheduleStatus;
    }

    public void setScheduleStatus(ChallengeStatus scheduleStatus) {
        this.scheduleStatus = scheduleStatus;
        this.updatedAt = getIndiaTimestamp();
    }

    public CompletionStatus getCompletion() {
        return completion;
    }

    public void setCompletion(CompletionStatus completion) {
        this.completion = completion;
        this.updatedAt = getIndiaTimestamp();
    }

    public Integer getSuccessPercent() {
        return successPercent;
    }

    public void setSuccessPercent(Integer successPercent) {
        this.successPercent = successPercent;
        this.updatedAt = getIndiaTimestamp();
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<ChallengeHabits> getChallengeHabits() {
        return challengeHabits;
    }

    public void setChallengeHabits(List<ChallengeHabits> challengeHabits) {
        this.challengeHabits = challengeHabits;
    }
}



